name: Trunk Full Check

permissions:
  contents: read

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  trunk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Trunk Code Quality
        uses: trunk-io/trunk-action@v1
