name: Trunk Full Check

permissions:
  contents: read

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  trunk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Trunk CLI
        run: |
          curl -L https://github.com/trunkhq/trunk/releases/latest/download/trunk-linux-amd64 -o trunk
          chmod +x trunk
          sudo mv trunk /usr/local/bin/

      - name: Run Full Check
        run: trunk check --all
