# SOPS configuration for age encryption
creation_rules:
  - path_regex: \.encrypted$
    age: >-
      age1qv5yxcpm8pzdxquly74hneemux2zg2vll6arc766s0zwk9tfuq3saukdju
    encrypted_regex: '^(data|sops|keys|mac)$'
